steps:
  # Step 1: Build - JAR
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'test', 'package', '-X']
    id: 'build'

  # Step 2: Deploy - JAR - Artifact Registry
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['deploy', '-s', 'settings.xml', '-DskipTests']
    id: 'deploy-artifact'

  # Step 3: Upload - JAR - Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'target/Chat_Client-1.0.0.jar', 'gs://$_BUCKET_NAME/Chat_Client-$_VERSION.jar']
    id: 'upload-jar'

  # Step 4: Notify Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'build-status'
      - '--message'
      - 'Build $_VERSION completed. Download: gs://$_BUCKET_NAME/Chat_Client-$_VERSION.jar'
    id: 'notify'

substitutions:
  _BUCKET_NAME: chat-client-artifacts
  _VERSION: 1.0.1
options:
  logging: CLOUD_LOGGING_ONLY