steps:
  - name: 'maven:3.9.6-eclipse-temurin-21'
    args: ['--version']
    id: 'debug-jdk'
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-X']
    id: 'build'
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'target/Chat_Client-2.0-ALPHA.jar', 'gs://$_BUCKET_NAME/Chat_Client-$BUILD_ID.jar']
    id: 'upload-jar'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'build-status'
      - '--message'
      - 'Build $BUILD_ID completed. Download: gs://$_BUCKET_NAME/Chat_Client-$BUILD_ID.jar'
    id: 'notify'

substitutions:
  _BUCKET_NAME: chat-client-artifacts

options:
  logging: CLOUD_LOGGING_ONLY