steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(grep -m 1 "<version>" pom.xml | sed -E 's|.*<version>(.*)</version>.*|\1|')
        echo $VERSION > version.txt
        echo "Extracted version: $VERSION"
    id: 'get-version'

  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'test', 'package', '-X']
    id: 'build'

  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['deploy', '-s', 'settings.xml', '-DskipTests']
    id: 'deploy-artifact'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/chat-client-docker-repo/chat-client:$_VERSION', '.']
    id: 'docker-build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/chat-client-docker-repo/chat-client:$_VERSION']
    id: 'docker-push'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'target/Chat_Client-$(cat version.txt).jar', 'gs://$_BUCKET_NAME/Chat_Client-$(cat version.txt).jar']
    id: 'upload-jar'

  # Step 5: Notify via Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'build-status'
      - '--message'
      - 'Build $(cat version.txt) completed. Download: gs://$_BUCKET_NAME/Chat_Client-$(cat version.txt).jar'
    id: 'notify'

substitutions:
  _BUCKET_NAME: chat-client-artifacts
options:
  logging: CLOUD_LOGGING_ONLY