steps:
  # Step 1: Build - JAR
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'test', 'package', '-X']
    id: 'build'

  # Step 2: Deploy - JAR - Artifact Registry
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['deploy', '-s', 'settings.xml', '-DskipTests']
    id: 'deploy-artifact'
    waitFor: ['build']

  # Step 3: Notify - Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'build-status'
      - '--message'
      - '{"status": "SUCCESS", "id": "$BUILD_ID", "artifacts": {"objects": [{"name": "gs://$_BUCKET_NAME/$_VERSION/Chat_Client-$_VERSION.jar"}]}}'
    id: 'notify'
    waitFor: ['deploy-artifact']

substitutions:
  _BUCKET_NAME: chat-client-artifacts
  _VERSION: 2.1.2
options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: gs://$_BUCKET_NAME/$_VERSION/
    paths:
      - target/Chat_Client-$_VERSION.jar