steps:
  # Step 1: Build the JAR
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'test', 'package', '-X']
    id: 'build'

  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['deploy', '-s', 'settings.xml', '-DskipTests']
    id: 'deploy-artifact'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/chat-client-docker-repo/chat-client:$_VERSION', '.']
    id: 'docker-build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/chat-client-docker-repo/chat-client:$_VERSION']
    id: 'docker-push'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'target/Chat_Client-2.0-ALPHA.jar', 'gs://$_BUCKET_NAME/Chat_Client-$_VERSION.jar']
    id: 'upload-jar'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'build-status'
      - '--message'
      - 'Build $_VERSION completed. Download: gs://$_BUCKET_NAME/Chat_Client-$_VERSION.jar'
    id: 'notify'

substitutions:
  _BUCKET_NAME: chat-client-artifacts
  _VERSION: 1.0.2
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/chat-client-docker-repo/chat-client:$_VERSION'
options:
  logging: CLOUD_LOGGING_ONLY