steps:
  # Step 1: Build - JAR
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'test', 'package', '-X']
    id: 'build'

  # Step 2: Deploy - JAR - Artifact Registry
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['deploy', '-s', 'settings.xml', '-DskipTests']
    id: 'deploy-artifact'
    waitFor: ['build']

  # Step 3: Upload to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'target/Chat_Client-$_VERSION.jar', 'gs://$_BUCKET_NAME/$_VERSION/Chat_Client-$_VERSION.jar']
    id: 'upload-to-gcs'
    waitFor: ['deploy-artifact']

  # Step 4: Notify - Pub/Sub (now waits for GCS upload)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'build-status'
      - '--message'
      - '{"status": "SUCCESS", "id": "$BUILD_ID", "artifacts": {"objects": [{"name": "gs://$_BUCKET_NAME/$_VERSION/Chat_Client-$_VERSION.jar"}]}}'
    id: 'notify'
    waitFor: ['upload-to-gcs']

substitutions:
  _BUCKET_NAME: chat-client-artifacts
  _VERSION: 2.2.1
options:
  logging: CLOUD_LOGGING_ONLY